version: '3'
services:
  # Consul server on VM
  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/config/consul.hcl"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8600
      - 8502
      - 8500:8500
      - 8302
      - 8301
      - 8300
    networks:
      onprem:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  # Mesh gateway on VM
  gateway:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.5.0.3:8443",
      "-wan-address", "192.169.7.3:8443",
      "--",
      "-l", "debug"]
    networks:
      onprem:
        ipv4_address: 10.5.0.3
      wan:
        ipv4_address: 192.169.7.3

networks:
  onprem:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24