version: '3'
services:
  # Currency service
  currency:
    image: nicholasjackson/fake-service:v0.7.3
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: "currency (onprem)"
      MESSAGE: "currency response"
    networks:
      onprem:
        ipv4_address: 10.5.0.30
  currency_proxy:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/currency.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "currency-v1"]
    network_mode: "service:currency"

networks:
  wan:
    external:
      name: yard_wan
  onprem:
    external:
      name: yard_onprem