---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "service-b:9091"
    spec:
      containers:
      - name: service-a
        image: nicholasjackson/fake-service:v0.7.3
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "service-a (cloud)"
        - name: "MESSAGE"
          value: "service-a response"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9091"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090