---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  labels:
    app: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "payments:9091"
    spec:
      containers:
      - name: b
        image: nicholasjackson/fake-service:v0.7.3
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "b (space)"
        - name: "MESSAGE"
          value: "b response"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9091"