---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: backend
        image: nicholasjackson/fake-service:v0.7.7
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "backend (space)"
        - name: "MESSAGE"
          value: "backend response"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "false"